# SOPS configuration file
# This file tells sops how to encrypt/decrypt secrets

# Replace this with your actual age public key after running:
# age-keygen -o ~/.config/sops/age/keys.txt
keys:
  - &wesbragagt age1d3hfkar6wnrvunslnusqmgh7qu45dvmlup3ne264nvxk36kdx58q5c49w4

creation_rules:
  # Rules for encrypting files in the secrets directory
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *wesbragagt