version: '3.0'
services:
  new_computer:
    container_name: new_mac
    build: .
    volumes:
      - './local.yml:/home/wesbragagt/local.yml'
      - './ansible.cfg:/home/wesbragagt/ansible.cfg'
      - './tasks:/home/wesbragagt/tasks'
      - './Makefile:/home/wesbragagt/Makefile'
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
