version: '3.0'
services:
  new_computer:
    container_name: new_computer_macosx
    build:
      dockerfile: Dockerfile.macosx
      context: .
    volumes:
      - "./local.yml:/home/wesbragagt/local.yml"
      - "./tasks:/home/wesbragagt/tasks"
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
