version: '3.0'
services:
  new_computer:
    container_name: new_mac
    build: .
    volumes:
      - "./local.yml:/home/wesbragagt/local.yml"
      - "./tasks:/home/wesbragagt/tasks"
      - "./Makefile:/home/wesbragagt/Makefile"
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
