- name: Bootstrap a new computer
  hosts: localhost
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/neovim.yml
    - include: tasks/productivity.yml
