- name: Bootstrap a new computer
  hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    homebrew:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/neovim.yml
  - include: tasks/dotfiles.yml
  - include: tasks/productivity.yml
