- name: Bootstrap a new computer
  hosts: localhost
  gather_facts: yes
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include_tasks: tasks/nix.yml
      tags: ['nix', 'install']
    - include_tasks: tasks/ssh.yml
      tags: ['ssh', 'dotfiles']
    - include_tasks: tasks/git-setup.yml
      tags: ['git-setup']
    - include_tasks: tasks/zsh.yml
      tags: ['zsh']
    - include_tasks: tasks/keyd.yml
      tags: ['keyd']
    - include_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
