- name: Bootstrap a new computer
  hosts: localhost
  gather_facts: yes
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: Detect package manager
      include_tasks: tasks/package-manager-detection.yml
      tags: ['setup']
    
    - name: Install Nix if requested and not present
      include_tasks: tasks/nix-installation.yml
      when: install_nix is defined and install_nix
      tags: ['nix', 'install']
    
    - name: Update Homebrew
      shell: brew update
      when: detected_package_manager == "homebrew"
      environment:
        HOMEBREW_NO_AUTO_UPDATE: '1'
    
    - name: Update package cache (Pacman)
      community.general.pacman:
        update_cache: true
      when: detected_package_manager == "pacman"
      become: true
    
    - name: Update package cache (DNF)
      ansible.builtin.dnf:
        update_cache: true
      when: detected_package_manager == "dnf"
      become: true
    
    - name: Update package cache (APT)
      ansible.builtin.apt:
        update_cache: true
      when: detected_package_manager == "apt"
      become: true
    
    - name: Update Nix channels (if using Nix)
      shell: nix-channel --update
      when: detected_package_manager == "nix"
      failed_when: false
    
    - include_tasks: tasks/homebrew.yml
      tags: ['homebrew']
    - include_tasks: tasks/ssh.yml
      tags: ['ssh', 'dotfiles']
    - include_tasks: tasks/git-setup.yml
      tags: ['git-setup']
    - include_tasks: tasks/core.yml
      tags: ['core', 'install']
    - include_tasks: tasks/zsh.yml
      tags: ['zsh']
    - include_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
    - include_tasks: tasks/node.yml
      tags: ['node']
    - include_tasks: tasks/neovim.yml
      tags: ['neovim', 'install', 'dotfiles']
    - include_tasks: tasks/fonts.yml
      tags: ['fonts', 'install', 'optional']
