- name: Bootstrap a new computer
  hosts: localhost
  gather_facts: False
  tasks:
    - include: tasks/core.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/neovim.yml
    - include: tasks/productivity.yml
    - include: tasks/fonts.yml
