- name: Core dependencies part 1
  tags: &core_tags ['install', 'core']
  homebrew:
    name: ['fzf', 'ripgrep', 'bat']

- name: Core dependencies part 2
  tags: *core_tags
  homebrew:
    name: ['mmv', 'jq', 'lsd']

- name: Rust tool chain
  tags: *core_tags
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
