- name: Core dependencies part 1
  become: True
  become_user: "{{ansible_user_id}}"
  tags: &core_tags ['install', 'core']
  homebrew:
    name: ['fzf', 'ripgrep', 'bat', 'fd', 'wget']

- name: Core dependencies part 2
  become: True
  become_user: "{{ansible_user_id}}"
  tags: *core_tags
  homebrew:
    name: ['tmux' ,'jq', 'git-delta', 'gh', 'zoxide']

- name: Golang
  become: True
  become_user: "{{ansible_user_id}}"
  tags: *core_tags
  homebrew:
    name: ['golang']

- name: Add git delta config
  tags: *core_tags
  become: True
  become_user: "{{ansible_user_id}}"
  shell:
    cmd: |
      cat >> ~/.gitconfig<< EOF
          [core]
          pager = delta

          [interactive]
              diffFilter = delta --color-only
          [delta]
              navigate = true  # use n and N to move between diff sections
              line-numbers = true
              side-by-side = true
          [merge]
              conflictstyle = diff3
          [diff]
              colorMoved = default
          EOF
