- name: Load OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/os_{{ ansible_facts['distribution'] }}.yml"
    - "vars/os_defaults.yml"
  tags: &core_tags ['install', 'core']

- name: Install core packages
  "{{ package_manager_module }}":
    name: "{{ core_packages }}"
    state: "{{ package_manager_state }}"
    update_cache: "{{ package_manager_update_cache | default(omit) }}"
  become: True
  become_user: "{{ ansible_user_id if become_user_needed else omit }}"
  tags: *core_tags

- name: Add git delta config
  tags: *core_tags
  become: True
  become_user: "{{ansible_user_id}}"
  shell:
    cmd: |
      cat >> ~/.gitconfig<< EOF
          [core]
          pager = delta

          [interactive]
              diffFilter = delta --color-only
          [delta]
              navigate = true  # use n and N to move between diff sections
              line-numbers = true
              side-by-side = true
          [merge]
              conflictstyle = diff3
          [diff]
              colorMoved = default
          EOF
