- name: Load OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/os_{{ ansible_facts['distribution'] }}.yml"
    - "vars/os_defaults.yml"
  tags: &core_tags ['install', 'core']

- name: Install core packages (macOS)
  community.general.homebrew:
    name: "{{ core_packages }}"
    state: "{{ package_manager_state }}"
  become: True
  become_user: "{{ ansible_user_id }}"
  tags: *core_tags
  when: ansible_distribution == "MacOSX"

- name: Install core packages (Arch Linux)
  community.general.pacman:
    name: "{{ core_packages }}"
    state: "{{ package_manager_state }}"
    update_cache: "{{ package_manager_update_cache }}"
  become: True
  tags: *core_tags
  when: ansible_distribution == "Archlinux"

- name: Add git delta config
  tags: *core_tags
  become: True
  become_user: "{{ansible_user_id}}"
  shell:
    cmd: |
      cat >> ~/.gitconfig<< EOF
          [core]
          pager = delta

          [interactive]
              diffFilter = delta --color-only
          [delta]
              navigate = true  # use n and N to move between diff sections
              line-numbers = true
              side-by-side = true
          [merge]
              conflictstyle = diff3
          [diff]
              colorMoved = default
          EOF
