- name: Installing stow (macOS)
  become: True
  become_user: '{{ansible_user_id}}'
  shell: brew install stow
  tags: &dotfiles_tags ['install', 'dotfiles']
  when: ansible_distribution == "MacOSX"

- name: Installing stow (Arch Linux)
  become: True
  community.general.pacman:
    name: stow
    state: present
    update_cache: true
  tags: *dotfiles_tags
  when: ansible_distribution == "Archlinux"

- name: Installing stow (Fedora)
  become: True
  ansible.builtin.dnf:
    name: stow
    state: present
    update_cache: true
  tags: *dotfiles_tags
  when: ansible_distribution == "Fedora"

- name: Check for dotfiles cloned
  stat:
    path: ~/.dotfiles
  register: dotfiles_check
  tags: *dotfiles_tags

- name: Cloning .dotfiles
  shell: git clone --recurse-submodules https://github.com/wesbragagt/.dotfiles.git ~/.dotfiles
  when: not dotfiles_check.stat.exists
  tags: *dotfiles_tags

- name: Check for .zshrc
  stat:
    path: ~/.zshrc
  register: zshrc_check
  tags: *dotfiles_tags

- name: Delete these files first
  shell: rm -rf ~/.zshrc
  when: zshrc_check.stat.exists
  tags: *dotfiles_tags

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./setup.sh
  tags: *dotfiles_tags
