- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  shell: git clone https://github.com/wesbragagt/.dotfiles.git
  args:
    creates: $HOME/.dotfiles
  tags:
    - install
    - dotfiles
    - stow
    - clone

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./setup.sh
  tags:
    - install
    - dotfiles
    - stow
