- name: Check dotfiles
  stat:
    path: "/home/{{ansible_user_id}}/.dotfiles"
  register: dotfiles
  tags: &tags_for_dotfiles
    - dotfiles
    - install
    - stow

- name: Cloning .dotfiles
  shell: git clone https://github.com/wesbragagt/.dotfiles.git ~/.dotfiles
  when: dotfiles.stat.exists == False 
  tags: *tags_for_dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./setup.sh
  tags: *tags_for_dotfiles
