- name: Install Fonts (macOS)
  become: true
  become_user: "{{ansible_user_id}}"
  shell: |
    brew tap homebrew/cask-fonts
    brew install --cask --force font-hack-nerd-font font-fira-code-nerd-font
  tags: &fonts_tags
    - install
    - fonts
    - optional
  when: ansible_distribution == "MacOSX"

- name: Install Fonts (Arch Linux)
  become: true
  community.general.pacman:
    name: ['ttf-hack', 'ttf-fira-code']
    state: present
    update_cache: true
  tags: *fonts_tags
  when: ansible_distribution == "Archlinux"

- name: Install Fonts (Fedora)
  become: true
  ansible.builtin.dnf:
    name: ['hack-fonts', 'fira-code-fonts']
    state: present
    update_cache: true
  tags: *fonts_tags
  when: ansible_distribution == "Fedora"
