- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  tags: &git-setup ['git-setup']

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  tags: *git-setup

- name: Git Host Setup
  tags: *git-setup
  shell: ssh-keygen -F github.com || ssh-keyscan github.com >> ~/.ssh/known_hosts
