- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "wesbragagt@gmail.com"
  tags: &git-setup ['git-setup']

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "wesbragagt"
  tags: *git-setup
