---
- name: Install keyd (Linux only)
  become: true
  package:
    name: keyd
    state: present
  when: ansible_system == "Linux"
  tags: ['keyd']

- name: Enable and start keyd service
  become: true
  systemd:
    name: keyd
    enabled: yes
    state: started
    daemon_reload: yes
  when: ansible_system == "Linux"
  tags: ['keyd']