- name: Install neovim
  tags: &neovim_tags
    - install
    - core
    - dotfiles
    - zsh
    - node
    - neovim
  become: yes
  become_user: '{{ansible_user_id}}'
  shell: nix-env -if ./nix/neovim.nix
