- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node
- name: Install N
  become: true
  npm:
    name: n
    global: yes
  tags:
    - install
    - node
- name: Install correct version of Node
  become: true
  shell: n 16
  tags:
    - install
    - node
