- name: Install NPM
  retries: 3
  become: True
  become_user: '{{ansible_user_id}}'
  homebrew:
    name: ['npm']
  tags: &tags_for_node_tasks ['install', 'node']

- name: Check npm folder
  ignore_errors: True
  tags: *tags_for_node_tasks
  register: npm_folder_check
  stat:
    path: ~/.npm_global

- name: Create npm folder
  ignore_errors: True
  when: not npm_folder_check.stat.exists
  file:
    path: ~/.npm_global
    state: directory
    mode: 'u=rw,g=wx,o=rwx'
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  ignore_errors: True
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install basic npm packages
  tags: *tags_for_node_tasks
  shell: npm install --global typescript ts-node yarn jest @fsouza/prettierd eslint_d


- name: Install Node & Fnm
  ignore_errors: True
  retries: 3
  become: True
  become_user: '{{ansible_user_id}}'
  homebrew:
    name: ['node', 'fnm']
  tags: *tags_for_node_tasks
