- name: Install nodejs and npm
  become: yes
  become_user: "{{ansible_user_id}}"
  homebrew:
    name: ["node@14", "npm"]
  tags: &tags_for_node_tasks [ 'install', 'node']

- name: Create npm folder
  shell: mkdir ~/.npm_global
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install yarn
  npm:
    name: yarn
    global: true
  tags: *tags_for_node_tasks

- name: Install basic globals
  shell: npm install -g typescript ts-node
  tags: *tags_for_node_tasks
