  # https://github.com/Schniz/fnm
- name: Install fnm Node Version manager and npm
  become: yes
  become_user: "{{ansible_user_id}}"
  homebrew:
    name: ["fnm", "npm"]
  tags: &tags_for_node_tasks [ 'install', 'node']

- name: Source fnm
  shell: eval `fnm env`

- name: Create npm folder
  shell: mkdir ~/.npm_global
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install basic globals
  shell: npm install -g yarn typescript jest ts-node @appguru/luafmt prettier 
  tags: *tags_for_node_tasks
