- name: Install Node, NPM and NVM
  become: True
  become_user: '{{ansible_user_id}}'
  homebrew:
    name: ['node', 'npm', 'fnm']
  tags: &tags_for_node_tasks ['install', 'node']

- name: Create npm folder
  shell: rm -rf ~/.npm_global && mkdir ~/.npm_global
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install basic globals
  async: 120 # Maximum allowed time in Seconds
  poll: 05 # Polling Interval in Seconds
  shell: npm install -g yarn typescript jest ts-node prettier @fsouza/prettierd eslint_d
  tags: *tags_for_node_tasks
