  - name: Install n
    tags:
        - node
    shell: brew install n

  - name: n lts
    tags:
        - node
    shell: n lts

  - name: Yarn package manager
    tags:
        - node
        - package-manager

    shell: npm install yarn -g
