- name: Install Node, NPM and NVM
  become: yes
  become_user: "{{ansible_user_id}}"
  homebrew:
    name: ["node", "npm", "nvm"]
  tags: &tags_for_node_tasks ["install", "node"]

- name: Create node_version_manager folder
  shell: mkdir ~/.node_version_manager
  tags: *tags_for_node_tasks

- name: Create npm folder
  shell: mkdir ~/.npm_global
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install basic globals
  shell: npm install -g yarn typescript jest ts-node @appguru/luafmt prettier @fsouza/prettierd
  tags: *tags_for_node_tasks
