- name: Install Node, NPM and NVM
  become: yes
  become_user: '{{ansible_user_id}}'
  shell: nix-env -if ./nix/node.nix
  tags: &tags_for_node_tasks ['install', 'node']

- name: Set default node version
  tags: *tags_for_node_tasks
  become: yes
  become_user: '{{ansible_user_id}}'
  shell: fnm install 16 && fnm default 16

- name: Create node_version_manager folder
  shell: mkdir ~/.node_version_manager
  tags: *tags_for_node_tasks

- name: Create npm folder
  shell: mkdir ~/.npm_global
  tags: *tags_for_node_tasks

- name: Set NPM prefix
  shell: npm config set prefix ~/.npm_global
  tags: *tags_for_node_tasks

- name: Install basic globals
  async: 120 # Maximum allowed time in Seconds
  poll: 05 # Polling Interval in Seconds
  shell: npm install -g yarn typescript jest ts-node prettier @fsouza/prettierd eslint_d
  tags: *tags_for_node_tasks
