- name: Install productivity packages
  become: yes
  become_user: "{{ansible_user_id}}"
  homebrew:
    name: [ "tmux",  "fzf", "fd", "ripgrep", "bat", "jq", "jless" ]
  tags:
    - install
    - productivity
