- name: Install productivity packages
  tags:
    - productivity
  become: yes
  become_user: '{{ansible_user_id}}'
  homebrew:
    name:
      [
        'tmux',
        'tmuxinator',
        'fzf',
        'fd',
        'ripgrep',
        'mmv',
        'bat',
        'jq',
        'git-delta',
        'stylua',
        'lsd',
      ]

- name: Add git delta config
  tags:
    - productivity
  become: yes
  become_user: '{{ansible_user_id}}'
  shell:
    cmd: |
      cat >> ~/.gitconfig<< EOF
          [core]
          pager = delta

          [interactive]
              diffFilter = delta --color-only
          [delta]
              navigate = true  # use n and N to move between diff sections
              line-numbers = true
              side-by-side = true
          [merge]
              conflictstyle = diff3
          [diff]
              colorMoved = default
          EOF
