- name: Install packages
  become: true
  apt:
    name: [ "tmux",  "fzf", "fd-find", "ripgrep" ]
  tags:
    - install
    - productivity
- name: Symlink fd
  become: true
  shell: ln -s $(which fdfind) /usr/bin/fd
