- name: Install pyenv
  become: yes
  become_user: "{{ansible_user_id}}"
  homebrew:
    name: "pyenv"
  tags: &tags_for_python_tasks [ 'install', 'python']

- name: Build python 3.9.9
  shell: pyenv install 3.9.9 && echo "3.9.9" > ~/.pyenv/version
  tags: *tags_for_python_tasks
