- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags: &ssh_tags ['dotfiles', 'install', 'ssh']

- name: Install ssh key
  tags: *ssh_tags
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: Install ssh key public
  tags: *ssh_tags
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: Set authorized key took from file
  tags: *ssh_tags
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
