- name: Install ZSH
  tags: &tags_for_zsh_tasks ['zsh']
  become: True
  become_user: '{{ansible_user_id}}'
  homebrew: name=zsh

# This will set the variable the_user to the current running user, but will change the shell of that user using root.
# https://stackoverflow.com/questions/43560657/edit-current-users-shell-with-ansible
- name: Change shell to zsh
  tags: *tags_for_zsh_tasks
  become: True
  user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh

- name: Check that the oh-my-zsh exists
  tags: *tags_for_zsh_tasks
  stat:
    path: '/home/{{ansible_user_id}}/.oh-my-zsh'
  register: starship_stat

- name: Starship
  tags: *tags_for_zsh_tasks
  shell: curl -sS https://starship.rs/install.sh | sh
  when: not starship_stat.stat.exists
  become: True
  become_user: '{{ansible_user_id}}'
  ignore_errors: True

- name: Check that the autosuggestions exists
  become: True
  become_user: '{{ansible_user_id}}'
  tags: *tags_for_zsh_tasks
  stat:
    path: '~/{{ansible_user_id}}/.zsh/zsh-autosuggestions'
  register: autosuggestions

- name: Auto Suggestions
  become: True
  become_user: '{{ansible_user_id}}'
  tags: *tags_for_zsh_tasks
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions/
  when: not autosuggestions.stat.exists
