---
# ZSH setup - Uses system zsh as login shell to avoid SDDM issues
- name: Check if zsh is already installed
  shell: which zsh
  register: zsh_check
  failed_when: false
  changed_when: false
  tags: &tags_for_zsh_tasks ['zsh']

- name: Ensure zsh is installed (Arch Linux)
  become: True
  pacman:
    name: zsh
    state: present
  when: 
    - ansible_os_family == "Archlinux"
    - zsh_check.rc != 0
  tags: *tags_for_zsh_tasks

- name: Ensure zsh is installed (macOS/Darwin)
  homebrew:
    name: zsh
    state: present
  when: 
    - ansible_os_family == "Darwin"
    - zsh_check.rc != 0
  tags: *tags_for_zsh_tasks

- name: Detect system ZSH path
  shell: |
    if [ -f /usr/bin/zsh ]; then
      echo "/usr/bin/zsh"
    elif [ -f /bin/zsh ]; then
      echo "/bin/zsh"
    else
      # macOS default location
      echo "/bin/zsh"
    fi
  register: system_zsh_path
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Change login shell to system zsh
  become: True
  user:
    name: '{{ ansible_user_id }}'
    shell: '{{ system_zsh_path.stdout }}'
  tags: *tags_for_zsh_tasks
