---
# Simplified ZSH setup - packages and plugins now managed by Nix
# Only handles system-level shell change and cleanup tasks

- name: Detect ZSH path across platforms
  shell: which zsh
  register: zsh_path_result
  changed_when: false
  failed_when: false
  tags: &tags_for_zsh_tasks ['zsh']

- name: Set ZSH path variable
  set_fact:
    detected_zsh_path: "{{ zsh_path_result.stdout if zsh_path_result.rc == 0 else '/bin/zsh' }}"
  tags: *tags_for_zsh_tasks

- name: Change shell to zsh (cross-platform)
  become: True
  user:
    name: '{{ ansible_user_id }}'
    shell: '{{ detected_zsh_path }}'
  tags: *tags_for_zsh_tasks
