---
# ZSH setup - Uses system zsh as login shell to avoid SDDM issues
# Nix-managed zsh will be used in terminal sessions via exec

- name: Ensure system zsh is installed (Linux)
  become: True
  package:
    name: zsh
    state: present
  when: ansible_os_family != "Darwin"
  tags: &tags_for_zsh_tasks ['zsh']

- name: Detect system ZSH path
  shell: |
    if [ -f /usr/bin/zsh ]; then
      echo "/usr/bin/zsh"
    elif [ -f /bin/zsh ]; then
      echo "/bin/zsh"
    else
      # macOS default location
      echo "/bin/zsh"
    fi
  register: system_zsh_path
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Change login shell to system zsh
  become: True
  user:
    name: '{{ ansible_user_id }}'
    shell: '{{ system_zsh_path.stdout }}'
  tags: *tags_for_zsh_tasks
