---
# Default fallback variables for unsupported OSs
package_manager: package
package_manager_module: ansible.builtin.package
package_manager_state: present
package_manager_update_cache: false
become_user_needed: false

# Default core packages (generic names)
core_packages:
  - fzf
  - ripgrep
  - bat
  - fd
  - wget
  - tmux
  - jq
  - git-delta
  - gh
  - zoxide
  - golang

# Default ZSH packages
zsh_packages:
  - zsh

# Default Node.js packages
node_packages:
  - npm
  - node

# Default Neovim build dependencies
neovim_build_deps:
  - cmake
  - ninja
  - curl

# Default installation methods
starship_install_method: curl
starship_install_command: "curl -sS https://starship.rs/install.sh | sh"
bun_install_command: "curl -fsSL https://bun.sh/install | bash"
fnm_install_method: curl
fnm_install_command: "curl -fsSL https://fnm.vercel.app/install | bash"

# Default system shell path
system_shell_path: /bin/zsh