---
# Fedora-specific variables
package_manager: dnf
package_manager_module: ansible.builtin.dnf
package_manager_state: present
package_manager_update_cache: true
become_user_needed: false

# Core packages mapping
core_packages:
  - fzf
  - ripgrep
  - bat
  - fd-find
  - wget
  - tmux
  - jq
  - git-delta
  - gh  # GitHub CLI
  - zoxide
  - golang

# ZSH packages
zsh_packages:
  - zsh

# Node.js packages
node_packages:
  - nodejs
  - npm

# Neovim build dependencies
neovim_build_deps:
  - ninja-build
  - cmake
  - gcc
  - make
  - unzip
  - gettext
  - curl
  - glibc-gconv-extra

# Installation methods
starship_install_method: package
starship_package: starship
bun_install_command: "dnf install -y unzip && curl -fsSL https://bun.sh/install | bash"
fnm_install_method: curl
fnm_install_command: "dnf install -y unzip && curl -fsSL https://fnm.vercel.app/install | bash"

# System shell path
system_shell_path: /bin/zsh